baseURL: https://bonitoperoinutil.com/
languageCode: es-es
defaultContentLanguage: es
title: Bonito pero inútil
theme: toha-bpi

taxonomies:
  author: authors
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - AMP

languages:
  es:
    languageName: Español
    weight: 1
    permalinks:
      authors: /autores/:slug
      categories: /categorias/:slug

privacy:
  twitter:
    disable: false
    enableDNT: true
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

params:
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/main-logo.png
    favicon: /favicon.ico
  gitRepo: https://github.com/chusopr/bonitoperoinutil
  gitBranch: website
  enableBlogPost: true
  enableTOC: false
  enableSearch: true
  recentPostsNum: 6
  footer: false
  splash: false
  newsletter:
    enable: false
